### ISSUE TITLE
Models from Huggingface

### ISSUE THREAD

**Issue by mohrsalt** [JHU-CLSP/NeoCoder#1]
Hello, thank you for the great source repo for the paper!
Can I ask, when I am passing this model Qwen/Qwen2-1.5B-Instruct, it gives not supported error. Can I not use any model of my choice from HuggingFace?
Kindly help
Thank you

**Comment by yining610** [comment]
Hi, thanks for being interested to our work. You need to add model name and its associated class to the dict [__MODEL_TO_CLASS](https://github.com/JHU-CLSP/NeoCoder/blob/62b6805ec6ee9740574e985d3c8306794a47dba6/src/utils/configs.py#L50). I think the compatible class for Qwen would be `OpenModelHF`.
